developer-list:
  staffMembers:
    - id: 101
      name: Petr
      patronymic: Nikolayevich
      surName: Glinco
      StaffCompetenceGrade: D2
      StaffAppointment: DEVELOPER
    - id: 102
      name: Stas
      patronymic: Grigorievich
      surName: Kurban
      StaffCompetenceGrade: D3
      StaffAppointment: DEVELOPER
    - id: 103
      name: Igor
      patronymic: Ivanovich
      surName: Buiko
      StaffCompetenceGrade: D3
      StaffAppointment: DEVELOPER
    - id: 104
      name: Roman
      patronymic: Ignatievich
      surName: Chistoserdov
      StaffCompetenceGrade: D4
      StaffAppointment: DEVELOPER
    - id: 104
      name: Ivan
      patronymic: Vladimirovich
      surName: Tronin
      StaffCompetenceGrade: D3
      StaffAppointment: DEVELOPER